'use client';
import {useEffect,useMemo,useRef,useState} from 'react';

async function loadImg(file:File){const im=new Image();im.src=URL.createObjectURL(file);await im.decode();return im}
function saveCanvas(c:HTMLCanvasElement,name:string,type='image/png'){c.toBlob(b=>{if(!b)return;const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click()},type,.94)}

type Effect='brightness'|'contrast'|'sepia'|'invert'|'blur';
function ImageEffect({effect,label}:{effect:Effect,label:string}){const [file,setFile]=useState<File|null>(null),[value,setValue]=useState(effect==='blur'?4:effect==='brightness'||effect==='contrast'?120:100);const run=async()=>{if(!file)return;const im=await loadImg(file),c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d')!;g.filter=effect==='brightness'?`brightness(${value}%)`:effect==='contrast'?`contrast(${value}%)`:effect==='sepia'?`sepia(${value}%)`:effect==='invert'?`invert(${value}%)`:`blur(${value}px)`;g.drawImage(im,0,0);saveCanvas(c,`${effect}-image.png`)};return <div className="workspace"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><label className="settingField"><span>{label} 강도</span><input className="toolInput" type="range" min="0" max={effect==='blur'?30:200} value={value} onChange={e=>setValue(Number(e.target.value))}/><strong>{value}{effect==='blur'?'px':'%'}</strong></label><button className="primaryButton" disabled={!file} onClick={run}>{label} 적용 저장</button></div>}
export const ImageBrightness=()=> <ImageEffect effect="brightness" label="밝기"/>;
export const ImageContrast=()=> <ImageEffect effect="contrast" label="대비"/>;
export const ImageSepia=()=> <ImageEffect effect="sepia" label="세피아"/>;
export const ImageInvert=()=> <ImageEffect effect="invert" label="색상 반전"/>;
export const ImageBlur=()=> <ImageEffect effect="blur" label="블러"/>;
export function ImagePixelate(){const [file,setFile]=useState<File|null>(null),[px,setPx]=useState(12);const run=async()=>{if(!file)return;const im=await loadImg(file),small=document.createElement('canvas'),w=Math.max(1,Math.round(im.naturalWidth/px)),h=Math.max(1,Math.round(im.naturalHeight/px));small.width=w;small.height=h;small.getContext('2d')!.drawImage(im,0,0,w,h);const c=document.createElement('canvas');c.width=im.naturalWidth;c.height=im.naturalHeight;const g=c.getContext('2d')!;g.imageSmoothingEnabled=false;g.drawImage(small,0,0,c.width,c.height);saveCanvas(c,'pixelated.png')};return <div className="workspace"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><label className="settingField"><span>픽셀 크기</span><input className="toolInput" type="range" min="2" max="60" value={px} onChange={e=>setPx(Number(e.target.value))}/><strong>{px}</strong></label><button className="primaryButton" disabled={!file} onClick={run}>모자이크 저장</button></div>}
export function SquareImagePad(){const [file,setFile]=useState<File|null>(null),[color,setColor]=useState('#ffffff');const run=async()=>{if(!file)return;const im=await loadImg(file),s=Math.max(im.naturalWidth,im.naturalHeight),c=document.createElement('canvas');c.width=s;c.height=s;const g=c.getContext('2d')!;g.fillStyle=color;g.fillRect(0,0,s,s);g.drawImage(im,(s-im.naturalWidth)/2,(s-im.naturalHeight)/2);saveCanvas(c,'square-image.png')};return <div className="workspace"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><label className="settingField"><span>여백 색상</span><input className="toolInput" type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><button className="primaryButton" disabled={!file} onClick={run}>정사각형으로 저장</button></div>}
export function CircleCrop(){const [file,setFile]=useState<File|null>(null);const run=async()=>{if(!file)return;const im=await loadImg(file),s=Math.min(im.naturalWidth,im.naturalHeight),c=document.createElement('canvas');c.width=s;c.height=s;const g=c.getContext('2d')!;g.beginPath();g.arc(s/2,s/2,s/2,0,Math.PI*2);g.clip();g.drawImage(im,(s-im.naturalWidth)/2,(s-im.naturalHeight)/2);saveCanvas(c,'circle-crop.png')};return <div className="workspace"><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="primaryButton" disabled={!file} onClick={run}>원형 PNG 저장</button><p className="settingHint">원 밖의 영역은 투명하게 저장됩니다.</p></div>}

export function TextStats(){const [t,setT]=useState('첫 문장입니다. 두 번째 문장입니다.\n\n새 문단입니다.');const stats=useMemo(()=>({sentences:(t.match(/[^.!?\n]+[.!?]?/g)||[]).filter(x=>x.trim()).length,paragraphs:t.trim()?t.trim().split(/\n\s*\n/).length:0,lines:t?t.split('\n').length:0}),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><div className="resultPanel">문장 <strong>{stats.sentences}</strong> · 문단 <strong>{stats.paragraphs}</strong> · 줄 <strong>{stats.lines}</strong></div></div>}

function clamp255(n:number){return Math.max(0,Math.min(255,Math.round(n)))}
function rgb(hex:string){const v=parseInt(hex.slice(1),16);return [(v>>16)&255,(v>>8)&255,v&255]}
function hex(r:number,g:number,b:number){return '#'+[r,g,b].map(x=>clamp255(x).toString(16).padStart(2,'0')).join('')}
export function ColorMixer(){const [a,setA]=useState('#315efb'),[b,setB]=useState('#f97316'),[p,setP]=useState(50);const out=useMemo(()=>{const A=rgb(a),B=rgb(b),q=p/100;return hex(A[0]*(1-q)+B[0]*q,A[1]*(1-q)+B[1]*q,A[2]*(1-q)+B[2]*q)},[a,b,p]);return <div className="workspace"><div className="jsonEditorGrid"><input className="toolInput" type="color" value={a} onChange={e=>setA(e.target.value)}/><input className="toolInput" type="color" value={b} onChange={e=>setB(e.target.value)}/></div><input className="toolInput" type="range" min="0" max="100" value={p} onChange={e=>setP(Number(e.target.value))}/><div style={{height:120,borderRadius:16,background:out}}/><div className="resultPanel"><code>{out}</code></div></div>}
export function ComplementaryColor(){const [a,setA]=useState('#315efb');const out=useMemo(()=>{const [r,g,b]=rgb(a);return hex(255-r,255-g,255-b)},[a]);return <div className="workspace"><input className="toolInput" type="color" value={a} onChange={e=>setA(e.target.value)}/><div className="jsonEditorGrid"><div style={{height:120,borderRadius:16,background:a}}/><div style={{height:120,borderRadius:16,background:out}}/></div><div className="resultPanel">보색 <code>{out}</code></div></div>}
export function RgbSlider(){const [r,setR]=useState(49),[g,setG]=useState(94),[b,setB]=useState(251);const c=hex(r,g,b);return <div className="workspace">{([['R',r,setR],['G',g,setG],['B',b,setB]] as const).map(([n,v,s])=><label className="settingField" key={n}><span>{n}</span><input className="toolInput" type="range" min="0" max="255" value={v} onChange={e=>s(Number(e.target.value))}/><strong>{v}</strong></label>)}<div style={{height:120,borderRadius:16,background:c}}/><div className="resultPanel"><code>{c}</code> · rgb({r}, {g}, {b})</div></div>}
export function HslColorTool(){const [h,setH]=useState(225),[s,setS]=useState(96),[l,setL]=useState(59);const c=`hsl(${h} ${s}% ${l}%)`;return <div className="workspace">{([['H',h,setH,360],['S',s,setS,100],['L',l,setL,100]] as const).map(([n,v,set,max])=><label className="settingField" key={n}><span>{n}</span><input className="toolInput" type="range" min="0" max={max} value={v} onChange={e=>set(Number(e.target.value))}/><strong>{v}</strong></label>)}<div style={{height:120,borderRadius:16,background:c}}/><div className="resultPanel"><code>{c}</code></div></div>}
export function RgbaOpacity(){const [c,setC]=useState('#315efb'),[a,setA]=useState(.5);const [r,g,b]=rgb(c);return <div className="workspace"><input className="toolInput" type="color" value={c} onChange={e=>setC(e.target.value)}/><input className="toolInput" type="range" min="0" max="1" step="0.05" value={a} onChange={e=>setA(Number(e.target.value))}/><div style={{height:120,borderRadius:16,background:`rgba(${r},${g},${b},${a})`}}/><div className="resultPanel"><code>rgba({r}, {g}, {b}, {a})</code></div></div>}
export function TypeScale(){const [base,setBase]=useState(16),[ratio,setRatio]=useState(1.25);return <div className="workspace"><div className="jsonEditorGrid"><input className="toolInput" type="number" value={base} onChange={e=>setBase(Number(e.target.value))}/><input className="toolInput" type="number" step="0.05" value={ratio} onChange={e=>setRatio(Number(e.target.value))}/></div><div className="resultPanel">{[-2,-1,0,1,2,3,4].map(i=><div key={i} style={{fontSize:Math.max(8,base*Math.pow(ratio,i)),lineHeight:1.3}}>Aa {Math.round(base*Math.pow(ratio,i)*100)/100}px</div>)}</div></div>}
export function SpacingScale(){const [base,setBase]=useState(4);return <div className="workspace"><input className="toolInput" type="number" min="1" value={base} onChange={e=>setBase(Number(e.target.value))}/><div className="resultPanel">{[1,2,3,4,6,8,12,16].map(n=><div key={n} style={{display:'flex',gap:12,alignItems:'center'}}><code>{base*n}px</code><div style={{height:14,width:base*n,background:'#315efb',borderRadius:4}}/></div>)}</div></div>}
export function CssTriangle(){const [size,setSize]=useState(40),[color,setColor]=useState('#315efb'),[dir,setDir]=useState('up');const css=useMemo(()=>{const transparent=`${size}px solid transparent`,solid=`${size}px solid ${color}`;if(dir==='up')return `border-left:${transparent};border-right:${transparent};border-bottom:${solid};`;if(dir==='down')return `border-left:${transparent};border-right:${transparent};border-top:${solid};`;if(dir==='left')return `border-top:${transparent};border-bottom:${transparent};border-right:${solid};`;return `border-top:${transparent};border-bottom:${transparent};border-left:${solid};`},[size,color,dir]);return <div className="workspace"><div className="jsonEditorGrid"><select className="toolInput" value={dir} onChange={e=>setDir(e.target.value)}><option value="up">위</option><option value="down">아래</option><option value="left">왼쪽</option><option value="right">오른쪽</option></select><input className="toolInput" type="color" value={color} onChange={e=>setColor(e.target.value)}/></div><input className="toolInput" type="number" value={size} onChange={e=>setSize(Number(e.target.value))}/><div className="resultPanel"><code>width:0;height:0;{css}</code></div></div>}
export function CssTransformTool(){const [rotate,setRotate]=useState(0),[scale,setScale]=useState(1),[x,setX]=useState(0),[y,setY]=useState(0);const css=`translate(${x}px, ${y}px) rotate(${rotate}deg) scale(${scale})`;return <div className="workspace"><div style={{height:130,display:'grid',placeItems:'center'}}><div style={{width:80,height:80,background:'#315efb',borderRadius:12,transform:css}}/></div><div className="jsonEditorGrid"><input className="toolInput" type="number" value={rotate} onChange={e=>setRotate(Number(e.target.value))}/><input className="toolInput" type="number" step="0.1" value={scale} onChange={e=>setScale(Number(e.target.value))}/><input className="toolInput" type="number" value={x} onChange={e=>setX(Number(e.target.value))}/><input className="toolInput" type="number" value={y} onChange={e=>setY(Number(e.target.value))}/></div><div className="resultPanel"><code>transform: {css};</code></div></div>}
export function CssFilterTool(){const [blur,setBlur]=useState(0),[bright,setBright]=useState(100),[gray,setGray]=useState(0);const css=`blur(${blur}px) brightness(${bright}%) grayscale(${gray}%)`;return <div className="workspace"><div style={{height:130,borderRadius:16,background:'linear-gradient(135deg,#315efb,#f97316)',filter:css}}/>{[['blur',blur,setBlur,20],['brightness',bright,setBright,200],['grayscale',gray,setGray,100]].map(([n,v,s,m]:any)=><label className="settingField" key={n}><span>{n}</span><input className="toolInput" type="range" min="0" max={m} value={v} onChange={e=>s(Number(e.target.value))}/></label>)}<div className="resultPanel"><code>filter: {css};</code></div></div>}
export function TextShadowTool(){const [x,setX]=useState(2),[y,setY]=useState(2),[blur,setBlur]=useState(8),[color,setColor]=useState('#000000');const css=`${x}px ${y}px ${blur}px ${color}`;return <div className="workspace"><div style={{fontSize:42,fontWeight:800,textAlign:'center',padding:30,textShadow:css}}>Text Shadow</div><div className="jsonEditorGrid"><input className="toolInput" type="number" value={x} onChange={e=>setX(Number(e.target.value))}/><input className="toolInput" type="number" value={y} onChange={e=>setY(Number(e.target.value))}/><input className="toolInput" type="number" value={blur} onChange={e=>setBlur(Number(e.target.value))}/><input className="toolInput" type="color" value={color} onChange={e=>setColor(e.target.value)}/></div><div className="resultPanel"><code>text-shadow: {css};</code></div></div>}
export function ClampCalculator(){const [min,setMin]=useState(16),[max,setMax]=useState(32),[vw,setVw]=useState(3);return <div className="workspace"><div className="jsonEditorGrid"><input className="toolInput" type="number" value={min} onChange={e=>setMin(Number(e.target.value))}/><input className="toolInput" type="number" value={max} onChange={e=>setMax(Number(e.target.value))}/><input className="toolInput" type="number" value={vw} onChange={e=>setVw(Number(e.target.value))}/></div><div className="resultPanel"><code>font-size: clamp({min}px, {vw}vw, {max}px);</code></div></div>}
export function ViewportConverter(){const [v,setV]=useState(100),[viewport,setViewport]=useState(1440);return <div className="workspace"><div className="jsonEditorGrid"><label className="settingField"><span>px</span><input className="toolInput" type="number" value={v} onChange={e=>setV(Number(e.target.value))}/></label><label className="settingField"><span>뷰포트 너비 px</span><input className="toolInput" type="number" value={viewport} onChange={e=>setViewport(Number(e.target.value))}/></label></div><div className="resultPanel"><strong>{viewport?((v/viewport)*100).toFixed(4):0}vw</strong></div></div>}
export function GridTemplateGenerator(){const [cols,setCols]=useState(3),[gap,setGap]=useState(16);return <div className="workspace"><div className="jsonEditorGrid"><input className="toolInput" type="number" min="1" max="12" value={cols} onChange={e=>setCols(Number(e.target.value))}/><input className="toolInput" type="number" min="0" value={gap} onChange={e=>setGap(Number(e.target.value))}/></div><div style={{display:'grid',gridTemplateColumns:`repeat(${cols},1fr)`,gap}}>{Array.from({length:cols},(_,i)=><div key={i} style={{height:60,background:'#315efb',borderRadius:8}}/>)}</div><div className="resultPanel"><code>display:grid; grid-template-columns:repeat({cols}, 1fr); gap:{gap}px;</code></div></div>}

export function Stopwatch(){const [ms,setMs]=useState(0),[running,setRunning]=useState(false);const start=useRef(0);useEffect(()=>{if(!running)return;start.current=Date.now()-ms;const id=setInterval(()=>setMs(Date.now()-start.current),40);return()=>clearInterval(id)},[running]);const text=`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(Math.floor(ms/10)%100).padStart(2,'0')}`;return <div className="workspace"><div className="resultPanel" style={{fontSize:36,textAlign:'center'}}><strong>{text}</strong></div><div className="workspaceActions"><button className="primaryButton" onClick={()=>setRunning(v=>!v)}>{running?'일시정지':'시작'}</button><button className="secondaryButton" onClick={()=>{setRunning(false);setMs(0)}}>초기화</button></div></div>}
export function TimezoneConverter(){const [date,setDate]=useState(()=>new Date().toISOString().slice(0,16)),[zone,setZone]=useState('Asia/Seoul');const out=useMemo(()=>{const d=new Date(date);return Number.isNaN(d.getTime())?'':new Intl.DateTimeFormat('ko-KR',{timeZone:zone,dateStyle:'full',timeStyle:'long'}).format(d)},[date,zone]);return <div className="workspace"><input className="toolInput" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/><select className="toolInput" value={zone} onChange={e=>setZone(e.target.value)}>{['Asia/Seoul','Asia/Tokyo','Asia/Singapore','Europe/London','Europe/Paris','America/New_York','America/Los_Angeles','Australia/Sydney','UTC'].map(z=><option key={z}>{z}</option>)}</select><div className="resultPanel"><strong>{out}</strong></div><p className="settingHint">입력값은 현재 브라우저의 로컬 시간으로 해석한 뒤 선택한 시간대로 표시합니다.</p></div>}
export function WeekdayFinder(){const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));const out=useMemo(()=>new Intl.DateTimeFormat('ko-KR',{weekday:'long',year:'numeric',month:'long',day:'numeric'}).format(new Date(`${date}T12:00:00`)),[date]);return <div className="workspace"><input className="toolInput" type="date" value={date} onChange={e=>setDate(e.target.value)}/><div className="resultPanel"><strong>{out}</strong></div></div>}
