'use client';
import {useMemo,useState} from 'react';
export function CaseConverter(){const [t,setT]=useState('Hello World');const words=()=>t.trim().split(/[\s_-]+/).filter(Boolean);const set=(m:string)=>{const w=words();if(m==='upper')setT(t.toUpperCase());if(m==='lower')setT(t.toLowerCase());if(m==='title')setT(w.map(x=>x[0]?.toUpperCase()+x.slice(1).toLowerCase()).join(' '));if(m==='camel')setT(w.map((x,i)=>i?x[0]?.toUpperCase()+x.slice(1).toLowerCase():x.toLowerCase()).join(''));if(m==='snake')setT(w.map(x=>x.toLowerCase()).join('_'));if(m==='kebab')setT(w.map(x=>x.toLowerCase()).join('-'))};return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><div className="workspaceActions">{[['upper','대문자'],['lower','소문자'],['title','Title'],['camel','camelCase'],['snake','snake_case'],['kebab','kebab-case']].map(x=><button className="secondaryButton" key={x[0]} onClick={()=>set(x[0])}>{x[1]}</button>)}</div></div>}
export function DuplicateLineRemover(){const [t,setT]=useState('사과\n바나나\n사과');const out=useMemo(()=>[...new Set(t.split('\n'))].join('\n'),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><div className="resultPanel">{t.split('\n').length}줄 → {out.split('\n').length}줄</div><textarea className="toolTextarea" readOnly value={out}/><button className="secondaryButton" onClick={()=>navigator.clipboard.writeText(out)}>결과 복사</button></div>}
export function ListNumberer(){const [t,setT]=useState('첫 번째 항목\n두 번째 항목'),[style,setStyle]=useState('1');const out=useMemo(()=>t.split('\n').filter(Boolean).map((x,i)=>style==='bullet'?`• ${x}`:`${i+1}. ${x}`).join('\n'),[t,style]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><select className="toolInput" value={style} onChange={e=>setStyle(e.target.value)}><option value="1">1. 2. 3.</option><option value="bullet">• 글머리표</option></select><textarea className="toolTextarea" readOnly value={out}/></div>}
export function SlugMaker(){const [t,setT]=useState('나의 첫 웹 페이지');const out=useMemo(()=>t.normalize('NFKD').toLowerCase().trim().replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,''),[t]);return <div className="workspace"><input className="toolInput" value={t} onChange={e=>setT(e.target.value)}/><div className="resultPanel"><code>{out}</code></div><button className="secondaryButton" onClick={()=>navigator.clipboard.writeText(out)}>복사</button></div>}
export function PercentageCalculator(){const [a,setA]=useState(100),[b,setB]=useState(20);return <div className="workspace"><div className="jsonEditorGrid"><label className="settingField"><span>기준값</span><input className="toolInput" type="number" value={a} onChange={e=>setA(Number(e.target.value))}/></label><label className="settingField"><span>비율 (%)</span><input className="toolInput" type="number" value={b} onChange={e=>setB(Number(e.target.value))}/></label></div><div className="resultPanel">{a}의 {b}% = <strong>{a*b/100}</strong><br/>{b}는 {a}의 <strong>{a?b/a*100:0}%</strong></div></div>}
export function AspectRatioCalculator(){const [w,setW]=useState(1920),[h,setH]=useState(1080),[nw,setNw]=useState(1280);const nh=useMemo(()=>w?Math.round(nw*h/w):0,[w,h,nw]);return <div className="workspace"><div className="jsonEditorGrid"><input className="toolInput" type="number" value={w} onChange={e=>setW(Number(e.target.value))}/><input className="toolInput" type="number" value={h} onChange={e=>setH(Number(e.target.value))}/></div><label className="settingField"><span>새 가로 크기</span><input className="toolInput" type="number" value={nw} onChange={e=>setNw(Number(e.target.value))}/></label><div className="resultPanel">새 크기: <strong>{nw} × {nh}px</strong></div></div>}
export function DataUrlConverter(){const [out,setOut]=useState('');const load=(f?:File)=>{if(!f)return;const r=new FileReader();r.onload=()=>setOut(String(r.result));r.readAsDataURL(f)};return <div className="workspace"><input type="file" onChange={e=>load(e.target.files?.[0])}/><textarea className="toolTextarea" readOnly value={out} placeholder="파일을 선택하면 Data URL이 표시됩니다."/>{out&&<button className="secondaryButton" onClick={()=>navigator.clipboard.writeText(out)}>복사</button>}</div>}
