'use client';
import {useState} from 'react';
import {PDFDocument, StandardFonts, degrees, rgb} from 'pdf-lib';

async function loadPdf(file:File){return PDFDocument.load(await file.arrayBuffer())}
function download(bytes:Uint8Array,name:string){const blob=new Blob([bytes],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click()}
function parsePages(text:string,max:number){return [...new Set(text.split(/[ ,]+/).map(x=>Number(x)).filter(n=>Number.isInteger(n)&&n>=1&&n<=max))].map(n=>n-1)}

export function PdfRotatePages(){const [f,setF]=useState<File|null>(null),[angle,setAngle]=useState(90);const run=async()=>{if(!f)return;const pdf=await loadPdf(f);pdf.getPages().forEach(p=>p.setRotation(degrees((p.getRotation().angle+angle)%360)));download(await pdf.save(),'rotated.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><select className="toolInput" value={angle} onChange={e=>setAngle(Number(e.target.value))}><option value={90}>90°</option><option value={180}>180°</option><option value={270}>270°</option></select><button className="primaryButton" disabled={!f} onClick={run}>전체 페이지 회전 저장</button></div>}
export function PdfDeletePages(){const [f,setF]=useState<File|null>,[pages,setPages]=useState('2,4');const run=async()=>{if(!f)return;const pdf=await loadPdf(f);const ids=parsePages(pages,pdf.getPageCount()).sort((a,b)=>b-a);ids.forEach(i=>pdf.removePage(i));download(await pdf.save(),'deleted-pages.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><input className="toolInput" value={pages} onChange={e=>setPages(e.target.value)} placeholder="삭제할 페이지 예: 2,4,7"/><button className="primaryButton" disabled={!f} onClick={run}>선택 페이지 삭제</button></div>}
export function PdfReversePages(){const [f,setF]=useState<File|null>(null);const run=async()=>{if(!f)return;const src=await loadPdf(f),out=await PDFDocument.create(),idx=Array.from({length:src.getPageCount()},(_,i)=>src.getPageCount()-1-i),copied=await out.copyPages(src,idx);copied.forEach(p=>out.addPage(p));download(await out.save(),'reversed-pages.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><button className="primaryButton" disabled={!f} onClick={run}>페이지 순서 뒤집기</button></div>}
export function PdfDuplicatePage(){const [f,setF]=useState<File|null>(null),[page,setPage]=useState(1),[copies,setCopies]=useState(1);const run=async()=>{if(!f)return;const src=await loadPdf(f),out=await PDFDocument.create();const all=await out.copyPages(src,Array.from({length:src.getPageCount()},(_,i)=>i));all.forEach((p,i)=>{out.addPage(p);if(i===page-1)for(let c=0;c<copies;c++)out.addPage((out as any).copyPages?undefined as any:p)}); /* rebuild safely */ const rebuilt=await PDFDocument.create();for(let i=0;i<src.getPageCount();i++){const [p]=await rebuilt.copyPages(src,[i]);rebuilt.addPage(p);if(i===page-1)for(let c=0;c<copies;c++){const [dup]=await rebuilt.copyPages(src,[i]);rebuilt.addPage(dup)}}download(await rebuilt.save(),'duplicated-page.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><div className="jsonEditorGrid"><input className="toolInput" type="number" min="1" value={page} onChange={e=>setPage(Number(e.target.value))}/><input className="toolInput" type="number" min="1" max="20" value={copies} onChange={e=>setCopies(Number(e.target.value))}/></div><button className="primaryButton" disabled={!f} onClick={run}>페이지 복제 저장</button></div>}
function Parity({odd}:{odd:boolean}){const [f,setF]=useState<File|null>(null);const run=async()=>{if(!f)return;const src=await loadPdf(f),idx=Array.from({length:src.getPageCount()},(_,i)=>i).filter(i=>((i+1)%2===1)===odd),out=await PDFDocument.create(),pages=await out.copyPages(src,idx);pages.forEach(p=>out.addPage(p));download(await out.save(),odd?'odd-pages.pdf':'even-pages.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><button className="primaryButton" disabled={!f} onClick={run}>{odd?'홀수':'짝수'} 페이지만 저장</button></div>}
export const PdfOddPages=()=> <Parity odd/>; export const PdfEvenPages=()=> <Parity odd={false}/>;
export function PdfPageNumbers(){const [f,setF]=useState<File|null>(null),[size,setSize]=useState(12);const run=async()=>{if(!f)return;const pdf=await loadPdf(f),font=await pdf.embedFont(StandardFonts.Helvetica);pdf.getPages().forEach((p,i)=>{const text=`${i+1} / ${pdf.getPageCount()}`,w=font.widthOfTextAtSize(text,size);p.drawText(text,{x:(p.getWidth()-w)/2,y:18,size,font,color:rgb(.25,.25,.25)})});download(await pdf.save(),'page-numbers.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><input className="toolInput" type="number" min="8" max="40" value={size} onChange={e=>setSize(Number(e.target.value))}/><button className="primaryButton" disabled={!f} onClick={run}>페이지 번호 넣기</button></div>}
export function PdfWatermark(){const [f,setF]=useState<File|null>(null),[text,setText]=useState('WATERMARK'),[opacity,setOpacity]=useState(.25),[error,setError]=useState('');const run=async()=>{if(!f)return;try{const pdf=await loadPdf(f),font=await pdf.embedFont(StandardFonts.HelveticaBold);pdf.getPages().forEach(p=>{const size=Math.min(72,p.getWidth()/7),w=font.widthOfTextAtSize(text,size);p.drawText(text,{x:(p.getWidth()-w)/2,y:p.getHeight()/2,size,font,color:rgb(.5,.5,.5),opacity,rotate:degrees(35)})});download(await pdf.save(),'watermark.pdf');setError('')}catch{setError('현재 워터마크 문구는 영문·숫자 중심으로 입력해주세요.')}};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><input className="toolInput" value={text} onChange={e=>setText(e.target.value)} placeholder="WATERMARK"/><input className="toolInput" type="range" min="0.05" max="0.8" step="0.05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/><button className="primaryButton" disabled={!f} onClick={run}>워터마크 넣기</button>{error&&<div className="engineError">{error}</div>}</div>}
export function PdfMetadataEditor(){const [f,setF]=useState<File|null>(null),[title,setTitle]=useState(''),[author,setAuthor]=useState(''),[info,setInfo]=useState('');const inspect=async(file?:File)=>{if(!file)return;setF(file);const pdf=await loadPdf(file);setTitle(pdf.getTitle()||'');setAuthor(pdf.getAuthor()||'');setInfo(`페이지 ${pdf.getPageCount()}개 · 제목 ${pdf.getTitle()||'없음'} · 작성자 ${pdf.getAuthor()||'없음'}`)};const save=async()=>{if(!f)return;const pdf=await loadPdf(f);pdf.setTitle(title);pdf.setAuthor(author);download(await pdf.save(),'metadata-updated.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>inspect(e.target.files?.[0])}/>{info&&<div className="resultPanel">{info}</div>}<input className="toolInput" value={title} onChange={e=>setTitle(e.target.value)} placeholder="문서 제목"/><input className="toolInput" value={author} onChange={e=>setAuthor(e.target.value)} placeholder="작성자"/><button className="primaryButton" disabled={!f} onClick={save}>메타데이터 저장</button></div>}
export function PdfPageCount(){const [info,setInfo]=useState('');const inspect=async(file?:File)=>{if(!file)return;const pdf=await loadPdf(file);setInfo(`총 ${pdf.getPageCount()}페이지 · 파일 ${(file.size/1024/1024).toFixed(2)} MB`)};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>inspect(e.target.files?.[0])}/><div className="resultPanel"><strong>{info||'PDF를 선택하세요.'}</strong></div></div>}
export function PdfInsertBlank(){const [f,setF]=useState<File|null>(null),[after,setAfter]=useState(1);const run=async()=>{if(!f)return;const src=await loadPdf(f),out=await PDFDocument.create();for(let i=0;i<src.getPageCount();i++){const [p]=await out.copyPages(src,[i]);out.addPage(p);if(i===after-1)out.addPage([p.getWidth(),p.getHeight()])}download(await out.save(),'with-blank-page.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><label className="settingField"><span>몇 페이지 뒤에 빈 페이지 추가</span><input className="toolInput" type="number" min="1" value={after} onChange={e=>setAfter(Number(e.target.value))}/></label><button className="primaryButton" disabled={!f} onClick={run}>빈 페이지 추가</button></div>}
export function PdfPageSizeInfo(){const [rows,setRows]=useState<string[]>([]);const inspect=async(file?:File)=>{if(!file)return;const pdf=await loadPdf(file);setRows(pdf.getPages().map((p,i)=>`${i+1}페이지: ${p.getWidth().toFixed(1)} × ${p.getHeight().toFixed(1)} pt · ${p.getWidth()>p.getHeight()?'가로':'세로'}`))};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>inspect(e.target.files?.[0])}/><div className="resultPanel">{rows.map(x=><div key={x}>{x}</div>)}</div></div>}
function OrientationExtract({landscape}:{landscape:boolean}){const [f,setF]=useState<File|null>(null);const run=async()=>{if(!f)return;const src=await loadPdf(f),idx=src.getPages().map((p,i)=>({p,i})).filter(({p})=>(p.getWidth()>p.getHeight())===landscape).map(x=>x.i);if(!idx.length)return;const out=await PDFDocument.create(),pages=await out.copyPages(src,idx);pages.forEach(p=>out.addPage(p));download(await out.save(),landscape?'landscape-pages.pdf':'portrait-pages.pdf')};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>setF(e.target.files?.[0]||null)}/><button className="primaryButton" disabled={!f} onClick={run}>{landscape?'가로':'세로'} 방향 페이지만 저장</button></div>}
export const PdfLandscapePages=()=> <OrientationExtract landscape/>; export const PdfPortraitPages=()=> <OrientationExtract landscape={false}/>;
export function PdfOrientationReport(){const [out,setOut]=useState('');const inspect=async(file?:File)=>{if(!file)return;const pdf=await loadPdf(file);let portrait=0,landscape=0;pdf.getPages().forEach(p=>p.getWidth()>p.getHeight()?landscape++:portrait++);setOut(`전체 ${pdf.getPageCount()}페이지 · 세로 ${portrait} · 가로 ${landscape}`)};return <div className="workspace"><input type="file" accept="application/pdf" onChange={e=>inspect(e.target.files?.[0])}/><div className="resultPanel"><strong>{out||'PDF를 선택하세요.'}</strong></div></div>}
export function PdfCompareFiles(){const [rows,setRows]=useState<string[]>([]);const inspect=async(files:FileList|null)=>{if(!files)return;const arr=[] as string[];for(const f of Array.from(files).slice(0,10)){const pdf=await loadPdf(f);arr.push(`${f.name}: ${pdf.getPageCount()}페이지 · ${(f.size/1024/1024).toFixed(2)} MB`)}setRows(arr)};return <div className="workspace"><input type="file" accept="application/pdf" multiple onChange={e=>inspect(e.target.files)}/><div className="resultPanel">{rows.map(x=><div key={x}>{x}</div>)}</div></div>}
