'use client';
import {useMemo,useState} from 'react';
export function LineNumberer(){const [t,setT]=useState('첫째 줄\n둘째 줄');const out=useMemo(()=>t.split('\n').map((x,i)=>`${i+1}. ${x}`).join('\n'),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><textarea className="toolTextarea" readOnly value={out}/></div>}
export function TextReverser(){const [t,setT]=useState('안녕하세요');const out=useMemo(()=>Array.from(t).reverse().join(''),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><textarea className="toolTextarea" readOnly value={out}/></div>}
export function JoinSplitTool(){const [t,setT]=useState('사과\n바나나\n딸기'),[sep,setSep]=useState(', '),[mode,setMode]=useState<'join'|'split'>('join');const out=useMemo(()=>mode==='join'?t.split('\n').map(x=>x.trim()).filter(Boolean).join(sep):t.split(sep).map(x=>x.trim()).filter(Boolean).join('\n'),[t,sep,mode]);return <div className="workspace"><div className="workspaceActions"><button className="secondaryButton" onClick={()=>setMode('join')}>줄 → 한 줄</button><button className="secondaryButton" onClick={()=>setMode('split')}>구분자 → 줄</button></div><input className="toolInput" value={sep} onChange={e=>setSep(e.target.value)} placeholder="구분자"/><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><textarea className="toolTextarea" readOnly value={out}/></div>}
export function WordFrequency(){const [t,setT]=useState('사과 바나나 사과 딸기 바나나 사과');const rows=useMemo(()=>{const m=new Map<string,number>();t.toLowerCase().match(/[\p{L}\p{N}]+/gu)?.forEach(w=>m.set(w,(m.get(w)||0)+1));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,100)},[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><div className="resultPanel">{rows.map(([w,n])=><div className="resultRow" key={w}><span>{w}</span><strong>{n}</strong></div>)}</div></div>}
export function ReadingTime(){const [t,setT]=useState('읽을 텍스트를 입력하세요.');const words=useMemo(()=>t.trim()?t.trim().split(/\s+/).length:0,[t]);const mins=useMemo(()=>Math.max(1,Math.ceil(words/250)),[words]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><div className="resultPanel">단어 약 <strong>{words.toLocaleString()}개</strong> · 예상 읽기 시간 <strong>{mins}분</strong></div></div>}
export function WhitespaceVisualizer(){const [t,setT]=useState('공백  두 칸\n탭\t한 칸');const out=useMemo(()=>t.replace(/ /g,'·').replace(/\t/g,'→\t').replace(/\n/g,'↵\n'),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><textarea className="toolTextarea" readOnly value={out}/></div>}
export function EmojiRemover(){const [t,setT]=useState('안녕하세요 😊 오늘도 👍');const out=useMemo(()=>t.replace(/[\p{Extended_Pictographic}\uFE0F]/gu,''),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><textarea className="toolTextarea" readOnly value={out}/></div>}
export function SpecialCharRemover(){const [t,setT]=useState('Hello! 안녕@ 123#');const out=useMemo(()=>t.replace(/[^\p{L}\p{N}\s]/gu,''),[t]);return <div className="workspace"><textarea className="toolTextarea" value={t} onChange={e=>setT(e.target.value)}/><textarea className="toolTextarea" readOnly value={out}/></div>}
